import React, { useEffect, useState } from "react"
import Layout from '../components/Layout'
import { Link } from 'gatsby'



const TermsOfUse = () => {


  return (

    <Layout>

      <div className="section-holder">
        <div className="page-content section">
          <div className="container">
            <div className="section-title">
              <h2>Terms of Use</h2>
            </div>
            <p>Updated May 15, 2020</p>
            <p>Welcome to the document platform service offered by ApiGap, Inc., a Delaware corporation (“ApiGap”, “we,” “our” or “us”). The following terms and conditions (the “Terms”) govern your access to and/or use of the document platform, website and ApiGap’s content, services and products available at and/or through the website, including, but not limited to, electronic signature services, online uploads, display, delivery, acknowledgment, and limited storage services for documents and/or electronic contracts (collectively, the “Services”).</p>
            <h3>ARBITRATION NOTICE</h3>
            <p>ARBITRATION NOTICE: EXCEPT FOR CERTAIN TYPES OF DISPUTES DESCRIBED IN THE ARBITRATION CLAUSE SET FORTH HEREIN, YOU AGREE THAT DISPUTES BETWEEN YOU AND APIGAP WILL BE RESOLVED BY MANDATORY ARBITRATION AND YOU WAIVE ANY RIGHT TO PARTICIPATE IN A CLASS-ACTION LAWSUIT AND/OR CLASS-WIDE ARBITRATION.</p>
            <h3>ACCEPTANCE OF TERMS</h3>
            <p>The Services are offered subject to your acceptance of the terms and conditions contained herein and all other operating rules, policies (including, without limitation, Hipporello’s Privacy Policy) and procedures that may be published from time to time by ApiGap related to the Services, which shall be incorporated herein by reference. By accessing, registering for and/or using the Services in any manner you agree to the Terms. If you do not agree to the Terms, do not use the Services.</p>
            <h3>CHANGES</h3>
            <p>We may make changes to the Terms and/or our other operating rules, policies and/or procedures from time to time, in our sole and absolute discretion. We will notify you of any changes to the Terms by posting the updated Terms on ApiGap’s website and/or the Services, and we will revise the “Updated” date above. Any changes to our operating rules, policies and/or procedures shall be incorporated herein. It is your responsibility to review the Terms frequently and to remain informed of any changes to them. We may also provide you with additional forms of notice of modifications and/or updates as appropriate under the circumstances including but not limited to sending you an email informing you of the changes and/or by prominently posting notice of the changes on Hipporello’s website and/or Services. If you do not agree with the changes and/or modifications, you shall not use the Services after the effective date of the changes. The then-current version of the Terms will supersede all earlier versions. You agree that your continued use of the Services after such changes have been published will constitute your acceptance of such revised Terms and operating rules, policies and/or procedures (as applicable).</p>
            <h3>LICENSE TO USE OUR SERVICES</h3>
            <p>3.1. Ownership and Rights to Access and/or Use the Hipporello platform (the “Platform”), the Hipporello API (the “API”), and/or other services offered by Hipporello (collectively, the “Services”). By using the Services and subject to your compliance with the Terms: (i) ApiGap and our licensors grant to you a limited, personal, non-exclusive, non-transferable, revocable right to use and/or access the Services; and (ii) you agree not to reproduce, distribute, create derivative works from, publicly display, publicly perform, license, sell and/or re-sell any content, software, products and/or services obtained from and/or through the Services without the express prior written permission of ApiGap. Neither the Terms nor your access to and/or use of the Services transfers to you and/or any third party any rights, title and/or interest in any intellectual property rights related to the Services.</p>
            <p>3.2. Reservation of Rights. Our Services and those of our licensors are protected by applicable intellectual property laws, including United States copyright law and international treaties. Subject to the limited rights expressly granted hereunder, ApiGap and/or its third-party providers, licensors, and suppliers reserve all right, title and interest in and to the Services, including without limitation all related worldwide intellectual property rights. No rights are granted to you hereunder other than as expressly set forth herein.</p>
            <p>3.3. Availability of Content. We do not guarantee that any content will be made available on the Services. We reserve the right to, but do not have any obligation to, (i) remove, edit and/or modify any content in our sole discretion, at any time, without notice to you and for any reason (including, but not limited to, upon receipt of claims and/or allegations from third parties and/or authorities relating to such content and/or if we are concerned that you may have violated the Terms), and/or for no reason at all and (ii) remove or block any content from the Services.</p>
            <h3>SCOPE OF USE</h3>
            <p>4.1. Use of Services and Availability. ApiGap retains the right, in its sole and absolute discretion, to deny access to and/or use of the Services to anyone at any time and for any reason. While we use reasonable efforts to keep the Services accessible, the Services may be unavailable from time to time. You understand and agree that there may be interruptions to the Services and/or use of and/or access to your Account due to circumstances both within our control (e.g., routine maintenance) and outside of ApiGap’s control. You are solely responsible for ensuring that your access to and/or use of the Services is in compliance with all laws, rules and regulations applicable to you and the right to access and/or use the Services is revoked where your access to and/or use of the Services is prohibited. Further, the Services are offered only for your use, and not for the use and/or benefit of any third party.</p>
            <p>4.2. Creating an Account. To sign up, access and/or use the Services, you must create an account (an “Account”). Your Account requires you to (i) indicate agreement to the Terms, (ii) provide contact information, and (iii) submit any other form of authentication required during the registration process, as determined by ApiGap in its sole and absolute discretion. You agree not to create an Account and/or use the Services if you have been previously removed by us and/or banned from the Services. You agree that ApiGap will not be liable to you and/or to any third party for any suspension and/or termination of your Account and/or any refusal of any access to and/or use of the Services (or any portion thereof). You must provide accurate and complete information and keep your Account information updated. You shall not: (a) select and/or use as a username a name of another person with the intent to impersonate that person; (b) use as a username a name subject to any rights of a person other than you without appropriate authorization; and/or (c) use as a username a name that is otherwise offensive, vulgar and/or obscene. You are solely responsible for maintaining the security of your Account, and you are fully responsible for all activities that occur under your Account and any other actions taken in connection with your Account. Your Account is non-transferrable and may not be sold, combined and/or otherwise shared with any other person. If you violate the Terms we may terminate your account immediately. You must notify us immediately of any change in your eligibility to use the Services (including any changes to and/or revocation of any licenses from state authorities), breach of security and/or unauthorized access to and/or use of your Account. You should never publish, distribute and/or post login information for your Account. If we terminate your Account, you may not subscribe under a new Account unless we formally invite you. You must immediately notify ApiGap of any unauthorized uses of your Account or any other breaches of security. ApiGap will not be liable for any acts and/or omissions by you, including without limitation any damages of any kind incurred as a result of such acts and/or omissions.</p>
            <p>4.3. Restrictions. Except as expressly specified in the Terms, you shall not (i) modify, and/or make derivative works of, disassemble, reverse compile and/or reverse engineer any part of the Services; (ii) license, transfer, sell, rent, lease, distribute, assign, host, sublicense and/or otherwise commercially exploit the Services, in whole or in part; (iii) frame and/or utilize framing techniques to enclose any trademark, logo, and/or other portion of the Services (including images, text, page layout, and/or form); (iv) use any metatags and/or other “hidden text” using ApiGap’s name and/or trademarks; (v) use any manual and/or automated software, devices and/or other processes (including but not limited to spiders, robots, scrapers, crawlers, avatars, data mining tools or the like) to “scrape” and/or download data from any pages contained in the Services (except that we grant the operators of public search engines revocable permission to use spiders to copy materials from the Services for the sole purpose of and solely to the extent necessary for creating publicly available searchable indices of the materials, but not caches or archives of such); (vi) use and/or access the Services in order to build a similar and/or competitive website, product, and/or service; (vii) copy, reproduce, distribute, republish, download, display, post and/or transmit any part of the Services in any form and/or by any means; (viii) remove and/or destroy any copyright notices and/or other proprietary markings contained on and/or in the Services; (ix) intentionally hold ApiGap and/or their employees and/or directors up to public scorn, ridicule and/or defamation; (x) promote and/or provide information about illegal activities and/or physical harm and/or injury to any group, individual, institution and/or property; (xi) take any action that imposes or may impose (as determined by us in our sole and absolute discretion) an unreasonable and/or disproportionately large load on our (and/or our third party providers’) infrastructure; (xii) run any form of auto-responder and/or “spam” on the Services; (xiii) use the Services for any unlawful purpose and/or to violate any federal, state, international law, code of conduct and/or other guidelines which may be applicable to the Services provided; (xiv) access, store, distribute or transmit any viruses, malware, or other harmful material during the course of your use of the Service; and/or (xv) make the functionality of the Services available to multiple users through any means, including, but not limited to distribution of the Services or by uploading the Services to a network and/or file-sharing service and/or through any hosting, application services provider and/or any other type of service. You will comply with any technical restrictions on the Services that allow you to use the Services only in certain ways. Any unauthorized use of the Services terminates the rights granted by ApiGap pursuant to the Terms.</p>
            <h3>PAYMENT</h3>
            <p>You can purchase a monthly or annual plan and your credit card on file will be charged on a recurring basis. All fees, expenses and taxes due hereunder will be paid in U.S. dollars. All fees due and payable by you to ApiGap under the Terms must be paid in full without any deduction, set-off, counterclaim or withholding of any kind unless required by law. All fees due and payable under the Terms are exclusive of taxes, which will be added at the prevailing rate from time to time. When you sign up for a paid plan, you are agreeing to pay and take responsibility for all charges made in accordance with the chosen plan, and your subscription will automatically renew at the end of the subscription term unless you cancel as further set forth herein.</p>
            <p>5.1. Cancellation policy. Once a user submits a request for cancellation, no additional charges will be made. However, no refunds (prorated or otherwise) are provided upon cancellation. In the interest of fairness to all of our clients, no exceptions will be made.</p>
            <p>5.2. Evaluations, trials, and betas. We may offer certain Cloud Products (including some Atlassian Apps) to you at no charge, including free accounts, trial use and Beta Versions as defined below (collectively, “No-Charge Products”). Your use of No-Charge Products is subject to any additional terms that we specify and is only permitted during the Subscription Term we designate (or, if not designated, until terminated in accordance with these Terms). Except as otherwise set, the terms and conditions of these Terms of Use, fully apply to No-Charge Products. We may modify or terminate your right to use No-Charge Products at any time and for any reason in our sole discretion, without liability to you. You understand that any pre-release and beta Cloud Products, and any pre-release and beta features within generally available Cloud Products, that we make available (collectively, “Beta Versions”) are still under development, may be inoperable or incomplete and are likely to contain more errors and bugs than generally available Cloud Products. We make no promises that any Beta Versions will ever be made generally available. In some circumstances, we may charge a fee in order to allow you to access Beta Versions. All information regarding the characteristics, features or performance of any No-Charge Products (including Beta Versions) constitutes our Confidential Information. To the maximum extent permitted by applicable law, we disclaim all obligations or liabilities with respect to No-Charge Products, including any Support, warranty and indemnity obligations.</p>
            <p>5.3. Monthly plan billing. ApiGap’s monthly plans provide month-to-month access, with monthly charges being made each renewal day (the same day of the month that you originally signed up for the plan). Monthly plans automatically renew every month. If you cancel before an upcoming renewal day, you will have access to your Account through the end of the then-current month.</p>
            <p>5.4. Annual plan billing. ApiGap’s annual plans provide year-to-year access and a substantial savings over the month-to-month plan. Annual charges will be made each renewal date (the same date of the year that you originally signed up for the plan). Annual plans automatically renew every year thereafter. If you cancel before an upcoming renewal date, you will have access to your Account through the end of the then-current year.</p>
            <p>5.5. Failed charges; Suspension. If your credit card on file is closed or the Account information is changed, or if, for any reason, a charge is rejected, you shall immediately update your Account or supply a new payment account, as appropriate. If you are unable to update your credit card account with appropriate information, then ApiGap will send an invoice to you detailing the amount due. You must pay the amount due in full within seven (7) days after the date of the invoice. You agree to notify ApiGap in writing of any changes to your Account information or termination of any authorization at least thirty (30) days prior to the immediately subsequent billing date. In the event payment dates fall on a weekend or holiday, you understand that the payments may be executed on the next business day. ApiGap may, without liability to you, disable the password, Account and access to all or part of the Services if any fees are not paid within forty-five (45) days after such fees first becoming due and payable under the Terms. In the event of the foregoing, ApiGap shall not be obligated to provide any and/or all of the Services until such fees are paid in full. Accounts that have been terminated may be reactivated if valid payment information is entered and the card can be successfully processed for all charges accrued on the Account since the failed credit card charge.</p>
            <h3>USER CONTENT</h3>
            <p>6.1. You represent and warrant that: (i) any information and/or User Content you provide in connection with your access to and/or use of the Services is true, accurate and complete and you will maintain and update such information regularly; and (ii) you will respect the intellectual property, other information and all rights of ApiGap and others using the Services.</p>
            <p>6.2. User Content. All content you or your users upload, create, submit, distribute, and/or post to the Services, including but not limited to, document layouts, source code, pictures, video and other images, audio materials, graphics, document or data files, information relating to natural and other persons, messages, e-mail and other communications, files, texts, personalization settings and other information and/or content, which is or may be provided to ApiGap and/or placed on the user’s ApiGap profile page or inputted and/or uploaded by you via the Services (“User Content”) whether publicly posted or privately transmitted, is the sole responsibility of the person who originated such User Content. ApiGap has no responsibility and/or liability for the deletion and/or accuracy of any User Content; the failure to store, transmit and/or receive transmission of User Content; and/or the security, privacy, storage and/or transmission of other communications originating with and/or involving use of the Services. You hereby grant ApiGap a worldwide, perpetual, non-exclusive, royalty-free, perpetual, irrevocable, assignable, sub-licensable, transferable license to use, edit, modify, truncate, aggregate, reproduce, distribute, prepare derivative works of, display, and perform the User Content for purposes of providing the Services and allow ApiGap to use your name and logo for ApiGap’s marketing purposes. You alone are responsible for User Content, and once published, it cannot always be withdrawn. You represent that you own, and/or have the necessary permissions to use and authorize use of User Content as described in the Terms.</p>
            <p>6.3. Feedback. Please keep in mind that we do not seek any unsolicited ideas and/or materials for the Services. If you provide us (in a direct mail, email and/or otherwise) with any feedback, suggestions, improvements, enhancements, recommendations and/or feature requests relating to the Services (“Feedback”), then you further grant to ApiGap a worldwide, perpetual, irrevocable, royalty-free license to use, reproduce, perform, display, distribute, adapt, modify, re-format, create derivative works of, and otherwise commercially or non-commercially exploit in any manner it deems appropriate, any and all Feedback, and to sublicense the foregoing rights. ApiGap will treat any Feedback you provide to ApiGap as non-confidential and non-proprietary. You represent and warrant that you have all rights necessary to submit the Feedback.</p>
            <p>6.4. Content Provided by Others. The Services may contain User Content provided by other users and/or third parties. Please carefully choose the information that you post on, through and/or in connection with the Services. You assume all risks associated with User Content, including anyone’s reliance on its quality, accuracy, and/or reliability by you. We are not responsible for and do not control such User Content. ApiGap disclaims any and all liability for your disclosure of personally identifiable or confidential information you submit via the Services to other users. It is your responsibility to ensure that Services users to whom you submit personally identifiable or confidential information will take appropriate security and non-disclosure measures.</p>
            <h3>PROHIBITED USER CONTENT</h3>
            <p>You agree that you will not under any circumstances transmit any User Content (including software, text, images, or other information) that:</p>
            <p>(i) is unlawful and/or promotes unlawful activities;</p>
            <p>(ii) defames, harasses, abuses, threatens, or incites violence towards any individual or group;</p>
            <p>(iii) is pornographic, discriminatory and/or otherwise victimizes and/or intimidates an individual and/or group on the basis of religion, gender, sexual orientation, race, ethnicity, age and/or disability;</p>
            <p>(iv) is spam, is machine- or randomly-generated, constitutes unauthorized or unsolicited advertising, chain letters, any other form of unauthorized solicitation and/or any form of lottery and/or gambling;</p>
            <p>(v) contains and/or installs any viruses, worms, malware, Trojan horses and/or other content that is designed or intended to disrupt, damage and/or limit the functioning of any software, hardware, and/or telecommunications equipment and/or to damage and/or obtain unauthorized access to any data and/or other information of any third party;</p>
            <p>(vi) infringes on any proprietary right of any party, including patent, trademark, trade secret, copyright, right of publicity and/or other rights;</p>
            <p>(vii) impersonates any person or entity, including any of our employees or representatives; and/or</p>
            <p>(viii) violates the privacy of any third party.</p>
            <h3>REVIEW OF USER CONTENT BY APIGAP</h3>
            <p>8.1. Enforcement. ApiGap does not undertake to screen, review, edit, censor and/or otherwise filter and/or control User Content and/or the behavior of users of User Content and/or the Services. ApiGap may, but shall not be obliged to, review, either by manual and/or automated means, all User Content which is and/or may be uploaded on this Services, and monitor and/or review any areas of this Services where users transmit and/or post communications or communicate with each other or ApiGap (as applicable). We reserve the right (but have no obligation) to review any User Content, and to investigate and/or take appropriate action against you in our sole discretion if you violate the Terms and/or otherwise create liability for us or any other person. Such action may include without limitation removing and/or modifying your User Content, terminating your Account, and/or reporting you to law enforcement authorities.</p>
            <p>8.2. User Content Liability. ApiGap shall not be liable for any loss, deletion, removal and/or failure of delivery to the intended recipient of User Content, whether caused by computer virus, unauthorized access and/or otherwise. You are encouraged to retain a back-up copy of all User Content and you undertake that you shall do so in respect of all uploaded User Content. ApiGap reserves the right to deny access to this site and delete User Content at any time without notice.</p>
            <h3>NO LEGAL ADVICE; ELECTRONIC COMMUNICATION</h3>
            <p>9.1. No legal advice. The Services do not provide legal advice and ApiGap is not a law firm. Part of the Services may involve the making of contracts, and/or other legal relations and although we attempt to make sure our information is accurate and useful, we recommend you consult with a lawyer if you want legal advice. ApiGap does not offer any legal advice, legal opinions, recommendations, referrals, and/or counseling. ApiGap is not involved in agreements between you and other users.</p>
            <p>9.2. Local Laws. The use of the Services may be governed by the laws of different countries or regions, and you agree to abide by such local laws. You agree that your use of any electronic signatures will be as valid as any manual signatures, if authorized by local law, and you will ensure that your use of electronic signatures is in conformance with local laws and regulations.</p>
            <p>9.3. Electronic Communications. By using the Services, you agree to receive certain communications in connection with the Services. The communications between you and ApiGap use electronic means, whether you use the Services or send us emails, or whether ApiGap posts notices on the Services or communicates with you via email. For contractual purposes, you (i) consent to receive communications from ApiGap in an electronic form; and (ii) agree that all terms and conditions, agreements, notices, disclosures, and other communications that ApiGap provides to you electronically satisfy any legal requirement that such communications would satisfy if it were to be a hardcopy in writing. The foregoing does not affect your non-waivable rights.</p>
            <h3>TERM; TERMINATION</h3>
            <p>Subject to this Section, the Terms will remain in full force and effect while you access and/or use the Services. We may terminate your Account and/or your access to and/or use of all or any part of the Services at any time, with or without cause, with or without notice, effective immediately and without liability, which may involve deletion of your User Content associated with your Account from our databases. You agree that ApiGap will not be liable to you or to any third party for such removal. If you wish to terminate your Account, you may do so by following the instructions through your Account. ApiGap will not have any liability whatsoever to you for any termination of your rights under the Terms, including without limitation for termination of your Account and/or deletion of your User Content.</p>
            <h3>DISCLAIMER OF LIABILITY</h3>
            <p>11.1. ApiGap is under no obligation to become involved in any dispute that you have with other users and/or in any incident that you are party to with other users, or that are affected by and/or otherwise related to the Services.</p>
            <p>11.2. ApiGap disclaims all liability relating to any User Content, including any error, virus, defamation, libel, obscenity or inaccuracy contained in any User Content, whether or not arising under the laws of copyright, libel, privacy or otherwise, any prohibited User Content and any other User Content. You are solely responsible for any damage (including without limitation to the Services) resulting from use (and/or submission) of any User Content and/or the Services (including without limitation disputes and incidents described in the preceding sections) and related transactions and/or occurrences. ApiGap shall have no responsibility for unauthorized access to your Account, and/or automatic forwarding of messages and/or viruses (caused by viruses or otherwise).</p>
            <h3>NO LIABILITY FOR LOST DATA</h3>
            <p>Where ApiGap provides web hosting or other services via the Services involving the provision of computer storage space, and/or in relation to other relevant services, ApiGap reserves the right to impose and vary limits and/or restrictions (temporary or otherwise) on the use of the Service, including, without limitation, limits on the storage provided by reference to storage space, time/age of files, number and/or size of files, amount of data down and/or uploaded and/or any other criteria ApiGap may specify. Any content and/or materials which exceeds any such limit, may be deleted and/or not accepted for such storage, without liability to ApiGap.</p>
            <h3>DISCLAIMER OF WARRANTIES AND LIMITATION OF LIABILITY</h3>
            <p>13.1. DISCLAIMER OF WARRANTIES. THE SERVICES, AND ANY CONTENT, ARE PROVIDED BY ApiGap TO YOU ON AN “AS IS,” “AS AVAILABLE” BASIS, EXCEPT AS EXPRESSLY SET FORTH IN THE TERMS. ApiGap DOES NOT MAKE ANY OTHER WARRANTY OF ANY KIND WHETHER EXPRESS, STATUTORY AND/OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY, AND/OR FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, AND FROM COURSE OF DEALING, USAGE AND/OR TRADE PRACTICE, ALL OF WHICH ApiGap EXPRESSLY DISCLAIMS. WITHOUT LIMITING THE FOREGOING, ApiGap AND/OR ITS LICENSORS, PARTNERS AND CONTENT PROVIDERS MAKE NO WARRANTY THAT (I) THE SERVICES AND/OR CONTENT WILL MEET YOUR REQUIREMENTS AND/OR WILL BE CONSTANTLY AVAILABLE, UNINTERRUPTED, TIMELY, SECURE AND/OR ERROR-FREE; (II) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICES WILL BE EFFECTIVE, ACCURATE AND/OR RELIABLE; (III) ANY CONTENT AND/OR SOFTWARE AVAILABLE AT AND/OR THROUGH THE SERVICES IS FREE OF VIRUSES AND/OR OTHER HARMFUL COMPONENTS AND/OR (IV) ApiGap WILL NOT BE LIABLE AND/OR OTHERWISE RESPONSIBLE FOR ANY FAILURE AND/OR DELAY IN UPDATING THE SERVICES AND/OR ANY CONTENT. NO ADVICE AND/OR INFORMATION, WHETHER ORAL AND/OR WRITTEN, OBTAINED BY YOU FROM ApiGap AND/OR THROUGH YOUR ACCESS TO AND/OR USE OF THE SERVICES SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE TERMS.</p>
            <p>IF APPLICABLE LAW REQUIRES ANY WARRANTIES WITH RESPECT TO THE SERVICES, ALL SUCH WARRANTIES ARE LIMITED IN DURATION TO SIXTY (60) DAYS FROM THE DATE OF FIRST USE. NO ORAL OR WRITTEN INFORMATION OR ADVICE GIVEN BY ApiGap AND/OR ITS AUTHORIZED REPRESENTATIVES WILL CREATE A WARRANTY. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSION MAY NOT APPLY TO YOU.</p>
            <p>13.2. LIMITATION OF LIABILITY. IN NO EVENT SHALL ApiGap, ITS OFFICERS, DIRECTORS, EMPLOYEES, PARTNERS, LICENSORS, AND/OR SUPPLIERS BE LIABLE TO YOU AND/OR ANYONE ELSE FOR (I) ANY SPECIAL, INCIDENTAL, INDIRECT, CONSEQUENTIAL AND/OR PUNITIVE DAMAGES WHATSOEVER, INCLUDING THOSE RESULTING FROM LOSS OF USE, DATA AND/OR PROFITS, WHETHER OR NOT FORESEEABLE, REGARDLESS OF THE FORM OF ACTION, WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE), WARRANTY, STRICT LIABILITY, AND/OR ANY OTHER LEGAL OR EQUITABLE THEORY, EVEN IF ApiGap HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES IN ADVANCE; AND/OR (II) ANY BUGS, VIRUSES, TROJAN HORSES, AND/OR THE LIKE (REGARDLESS OF THE SOURCE OF ORIGINATION). THE FOREGOING SHALL APPLY DESPITE ANY NEGLIGENCE, MISCONDUCT, ERRORS AND/OR OMISSIONS BY ApiGap ITS EMPLOYEES, REPRESENTATIVES AND/OR AGENTS. BECAUSE SOME STATES DO NOT ALLOW THE EXCLUSION AND/OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL AND/OR INCIDENTAL DAMAGES, IN SUCH STATES, ApiGap’S LIABILITY IS LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW.</p>
            <p>ApiGap’S MAXIMUM AGGREGATE LIABILITY TO YOU FOR DIRECT DAMAGES THAT YOU SUFFER IN CONNECTION WITH THE SERVICES IS LIMITED TO THE AMOUNT PAID BY YOU TO ApiGap IN CONNECTION WITH THE SERVICES IN THE SIX (6) MONTH PERIOD IMMEDIATELY PRECEDING THE DATE OF THE CLAIM. THE LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN ApiGap AND YOU.</p>
            <h3>INDEMNITY AND WAIVER</h3>
            <p>14.1. Indemnification. You will defend, indemnify and hold ApiGap, our suppliers and licensors, and our respective subsidiaries, affiliates, officers, agents, employees, representatives, and assigns harmless from all demands, proceedings, losses, costs, damages, awards, fees, expenses, and/or liabilities of any nature including without limitation reasonable attorneys’ fees, that arise from and/or relate to (i) your use of the Services and/or inability to use the Services; (ii) your User Content; (iii) your violation of the Terms, (iv) your violation of any rights of a third party through use of the Services or User Content; (v) fraud you commit and/or your intentional misconduct and/or negligence (vi) your interaction with any other user; and/or (vii) your use of the Services that is in violation of any applicable privacy law. We reserve the right to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will assist and cooperate with us in asserting any available defenses. You agree not to settle any matter without the prior written consent of ApiGap. ApiGap will use reasonable efforts to notify you of any such claim, action or proceeding upon becoming aware of it.</p>
            <p>14.2. Waiver. You hereby forever discharge and release us, our affiliates and each of our and their respective employees, contractors, directors, suppliers and representatives from, and hereby waive and relinquish, each and every past, present and future dispute, claim, controversy, demand, right, obligation, liability, action and cause of action of every kind and nature (including personal injuries, death, and property damage), that has arisen or arises directly or indirectly out of, and/or that relates directly or indirectly to: (i) the Services; (ii) any inaccurate, incomplete, unreliable, illegal or infringing content posted on the Services, whether caused by us or any user of the Services, or by any of the equipment or programming associated with or utilized in the Services; (iii) the conduct, whether online or offline, of any user; (iv) any injury, loss or damage caused by another user or User Content posted on the Services, whether online or offline; and (v) any error, omission, interruption, deletion, defect, delay in operation and/or transmission, communications line failure, theft and/or destruction and/or unauthorized access to, and/or alteration of, the Services users’ communications.</p>
            <p>IF YOU ARE A CALIFORNIA RESIDENT, YOU HEREBY WAIVE CALIFORNIA CIVIL CODE SECTION 1542 IN CONNECTION WITH THE FOREGOING, WHICH STATES: “A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH IF KNOWN BY HIM OR HER MUST HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR.”</p>
            <h3>LINKS</h3>
            <p>The Services may integrate with and/or provide links to various other independent third-party products and/or services (“Linked Sites”) that may be of interest to you and are for your convenience only. ApiGap does not control and/or endorse such Linked Sites and is not responsible for their content nor is it responsible for the accuracy and/or reliability of any information, data, opinions, advice and/or statements contained within such Linked Sites. You will need to make your own independent judgment regarding your interaction with Linked Sites at your own risk. We encourage you to be aware when you leave the Services and to read the terms and conditions and privacy policy of each Linked Site that you visit. ApiGap reserves the right to terminate any link and/or linking program at any time in its sole and absolute discretion. We disclaim all warranties, express and implied, as to the accuracy, validity and legality and/or otherwise of any materials and/or information contained on such Linked Sites.</p>
            <h3>MISCELLANEOUS</h3>
            <p>16.1. Entire Agreement; Conflict. Unless otherwise agreed to by ApiGap and you in writing, the Terms (including without limitation the terms and conditions set forth herein and ApiGap’s operating rules, policies and/or procedures as described above) constitutes the entire agreement between ApiGap and you concerning the subject matter hereof.</p>
            <p>16.2. Governing Law. Except to the extent applicable law, if any, provides otherwise, this Agreement and any access to or use of the Services will be governed by the laws of the State of Delaware, U.S.A., excluding its conflict of law provisions.</p>
            <p>16.3. Arbitration. Except for claims for injunctive or equitable relief or claims regarding intellectual property rights (which may be brought in any competent court without the posting of a bond), any dispute arising under the Terms shall be finally settled in accordance with the Comprehensive Arbitration Rules (“Rules”) of the Judicial Arbitration and Mediation Service, Inc. (“JAMS”) by three arbitrators appointed in accordance with such Rules. The arbitration shall take place in Delaware, in the English language and the arbitral decision may be enforced in any court. The prevailing party in any action or proceeding to enforce the Terms shall be entitled to costs and attorneys’ fees. You can opt-out and decline this agreement to arbitrate by contacting ApiGap within thirty (30) days from the date that you first became subject to this arbitration provision (i.e.: the date you initially accepted the Terms).</p>
            <p>(i) Waiver of Jury Trial. THE PARTIES HEREBY WAIVE THEIR CONSTITUTIONAL AND STATUTORY RIGHTS TO GO TO COURT AND HAVE A TRIAL IN FRONT OF A JUDGE OR A JURY, instead electing that all claims and disputes shall be resolved by arbitration. Arbitration procedures are typically more limited, more efficient and less costly than rules applicable in court and are subject to very limited review by a court. In the event any litigation should arise between you and ApiGap in any state or federal court in a suit to vacate or enforce an arbitration award or otherwise, YOU AND ApiGap WAIVE ALL RIGHTS TO A JURY TRIAL, instead electing that the dispute be resolved by a judge.</p>
            <p>(ii) Waiver of Class or Consolidated Actions. ALL CLAIMS AND DISPUTES WITHIN THE SCOPE OF THIS SECTION 16.3 MUST BE ARBITRATED OR LITIGATED ON AN INDIVIDUAL BASIS AND NOT ON A CLASS BASIS, AND CLAIMS OF MORE THAN ONE CUSTOMER OR USER CANNOT BE ARBITRATED OR LITIGATED JOINTLY OR CONSOLIDATED WITH THOSE OF ANY OTHER CUSTOMER OR USER. In the event that this Section is deemed invalid or unenforceable neither you nor we are entitled to arbitration and instead claims and disputes shall be resolved in a court located in Delaware.</p>
            <p>16.4. Reference. You agree that we may reference you as our customer, and that we may reasonably use, on a royalty-free basis, your trademark and/or logo for such purpose.</p>
            <p>16.5. Severability. If any part of the Terms is held invalid or unenforceable, that part will be construed to reflect the parties’ original intent, and the remaining portions will remain in full force and effect. A waiver by either party of any term or condition of the Terms and/or any breach thereof, in any one instance, will not waive such term and/or condition or any subsequent breach thereof.</p>
            <p>16.6. Assignment. You may not assign your rights under the Terms to any other party without ApiGap’s express prior written consent; ApiGap may assign its rights under the Terms without condition. The Terms will be binding upon and will inure to the benefit of the parties, their successors and permitted assigns.</p>
            <p>16.7. Force Majeure. Except for payment obligations, neither ApiGap nor Customer will be liable by reason of any failure or delay in the performance of its obligations on account of events beyond the reasonable control of a party, which may include denial-of-service attacks, a failure by a third party hosting provider or utility provider, shortages, riots, fires, acts of God, war, strikes, terrorism, and governmental action.</p>
            <p>16.8. Survival. All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, licenses of User Content, ownership provisions, warranty disclaimers, indemnity provisions and limitations of liability.</p>
            <p>16.9. No Waiver. No waiver by either you and/or ApiGap of any breach and/or default and/or failure to exercise any right allowed under the Terms is a waiver of any preceding and/or subsequent breach and/or default and/or a waiver and/or forfeiture of any similar and/or future rights under the Terms.</p>
            <h3>CONTACT</h3>
            <p>If you would like to request additional information regarding the Terms or for any questions regarding a commercial relationship with ApiGap, please contact us at <a href="mailto:legal@hipporello.com" target="_blank" rel="noopener noreferrer">legal@hipporello.com</a>.</p>
          </div>
        </div>
      </div>


    </Layout>
  )
}

export default TermsOfUse
